### PR TITLE
Fix quotes

### PR DESCRIPTION
**Pull request by lukechilds**
@sindresorhus @kevva can we merge this without messing up translations on Crowdin?

### CODE REVIEW

**Comment by sindresorhus** [comment]
What does this fix?

**Comment by sindresorhus** [comment]
> can we merge this without messing up translations on Crowdin?

I have a feeling it will mess it up, at least the word inside the quotes...

**Comment by lukechilds** [comment]
>What does this fix?

Currently it literally shows the text `&qoute;as is&qoute;` instead of `"as is"`.

>I have a feeling it will mess it up, at least the word inside the quotes...

😕

**Comment by kevva** [comment]
If we don't want to break any translation strings we could use `dangerouslySetInnerHTML` for this one so that the HTML entities gets rendered correctly.

**Comment by sindresorhus** [comment]
I'm gonna test and see if we can do this in a non-breaking way without using `dangerouslySetInnerHTML`.

**Pull request merged**
