### PR TITLE
Add dashboard intro

### PR DESCRIPTION
**Pull request by lukechilds**
Hopefully this will notify all users of the risks and make them aware of the maturity of the software.

MIT license should cover us for any legal disputes but @pondsea wanted me to explicitly bring it up here too. I give a breif summary about no warranty/liability and state that "By using HyperDEX you are agreeing to the terms of the MIT License".

I think that should be more than enough.

screen shot 2018-06-29 at 3 10 01 pm

The screenshot was taken with localisation disabled. Using the localisation files the text gets a bit garbled. I tried to copy the `<n>` pattern I'd seen in other localisation files but it doesn't look like I got it right. Is this a standardised format? Is there an automatic conversion tool we can use instead of manually creating the `<n>` tags.

Also, suggestions for text modifications welcome.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Is there an automatic conversion tool we can use instead of manually creating the <n> tags.

Not sure, but we definitely need that. See: https://github.com/hyperdexapp/hyperdex/issues/390

**Comment by sindresorhus** [comment]
> I tried to copy the <n> pattern I'd seen in other localisation files but it doesn't look like I got it right.

I think the numbers have to be unique for each tag.

**Comment by sindresorhus** [comment]
Travis is failing because of some lint error.

**Comment by sindresorhus** [comment]
The text looks good.

**Comment by lukechilds** [comment]
Hmmn, I tried using unique tag names and it messed it up even more 🤔.

Lint issue fixed.

Do you know what the actual format is called, like is it a i18n standard thing? I can't find any information on it.

**Comment by sindresorhus** [comment]
I think it's just specific to the `react-i18next` module. Not much info in the docs either: https://react.i18next.com/components/trans-component

**Comment by sindresorhus** [comment]
> Hmmn, I tried using unique tag names and it messed it up even more 🤔.

What does it look like messed up? I'm not able to reproduce that.

**Comment by lukechilds** [comment]
I see this:

screen shot 2018-06-29 at 10 21 50 pm

**Comment by kevva** [comment]
Best way to get it right is to just wrap it in the `Trans` component without adding a translation for it. Then it'll report in the console that a translation is missing, and print it with the correct formatting.

**Comment by lukechilds** [comment]
Cheers @kevva That sorted it.

**Comment by lukechilds** [comment]
I think this should be good to merge now. Then we can get on translations ASAP.

**Pull request merged**
